# The maximum number of homes a player can set.
max-homes: 15

# Worlds where the end portal is disabled.
disabled-end-portal-worlds:
  - "jass:archive"

# Worlds where fly is enabled by default.
fly-worlds:
  - "jass:archive"
  - "jass:lobby"

# Flight permission advancement
fly-advancement: "jass:test"

# Namespaced key of the custom enchantments.
telekinesis: "jass:test1"
smelter: "jass:test2"
lumberjack: "jass:test3"
tunneller: "jass:test5"
spawner-pickup: "jass:test6"
egg-collector: "jass:test7"
replant: "jass:test8"