# The maximum number of homes a player can set.
max-homes: 15

# Worlds where the end portal is disabled.
disabled-end-portal-worlds:
  - "jass:archive"

# Worlds where fly is enabled by default.
fly-worlds:
  - "jass:archive"
  - "jass:lobby"

# Flight permission advancement
fly-advancement: "jass:test"

# Namespaced key of the custom enchantments.
telekinesis: "jass:test1"
smelter: "jass:test2"
lumberjack: "jass:test3"
gem-connoisseur: "jass:test4"
tunneller: "jass:test5"
spawner-pickup: "jass:test6"
egg-collector: "jass:test7"
replant: "jass:test8"

# Drop rates for gem-connoisseur. Each entry is a 1-in-N chance per block mined.
gem-connoisseur-rates:
  1:
    stone:
      emerald: 1250
      diamond: 1094
      lapis_lazuli: 938
      redstone: 781
      gold_ingot: 625
      iron_ingot: 469
      copper_ingot: 312
      coal: 156
    deepslate:
      emerald: 1125
      diamond: 985
      lapis_lazuli: 845
      redstone: 706
      gold_ingot: 565
      iron_ingot: 425
      copper_ingot: 285
      coal: 145
    netherrack:
      quartz: 938
      gold_ingot: 469
  2:
    stone:
      emerald: 1000
      diamond: 875
      lapis_lazuli: 750
      redstone: 625
      gold_ingot: 500
      iron_ingot: 375
      copper_ingot: 250
      coal: 125
    deepslate:
      emerald: 900
      diamond: 788
      lapis_lazuli: 676
      redstone: 565
      gold_ingot: 452
      iron_ingot: 340
      copper_ingot: 228
      coal: 116
    netherrack:
      quartz: 750
      gold_ingot: 375
  3:
    stone:
      emerald: 800
      diamond: 700
      lapis_lazuli: 600
      redstone: 500
      gold_ingot: 400
      iron_ingot: 300
      copper_ingot: 200
      coal: 100
    deepslate:
      emerald: 720
      diamond: 630
      lapis_lazuli: 541
      redstone: 452
      gold_ingot: 362
      iron_ingot: 272
      copper_ingot: 182
      coal: 93
    netherrack:
      ancient_debris: 1000
      quartz: 600
      gold_ingot: 300