package me.beeliebub.tweaks.commands;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.minimessage.MiniMessage;
import io.papermc.paper.registry.RegistryAccess;
import io.papermc.paper.registry.RegistryKey;
import org.bukkit.Color;
import org.bukkit.FireworkEffect;
import org.bukkit.NamespacedKey;
import org.bukkit.block.banner.Pattern;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BannerMeta;
import org.bukkit.inventory.meta.BookMeta;
import org.bukkit.inventory.meta.Damageable;
import org.bukkit.inventory.meta.EnchantmentStorageMeta;
import org.bukkit.inventory.meta.FireworkMeta;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.meta.LeatherArmorMeta;
import org.bukkit.inventory.meta.PotionMeta;
import org.bukkit.inventory.meta.SkullMeta;
import org.bukkit.persistence.PersistentDataContainer;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.potion.PotionEffect;

import java.util.List;
import java.util.Map;
import java.util.Set;

// Generates a paste-ready Java snippet that reconstructs an inventory's contents.
//
// Output layout: an imports header, a `buildItem` helper, and one block per non-empty slot.
// Adventure components serialize to MiniMessage strings (round-trippable, far more readable
// than the previous GSON JSON). Specialized ItemMeta types — Potion, Book, Firework, Skull,
// LeatherArmor, Banner, EnchantmentStorage — each have a dedicated branch so common NBT
// (effects, pages, fireworks, owners, dye colors, banner patterns, stored enchants) survives.
// PDC handling covers all primitive types plus byte/int/long arrays and nested TAG_CONTAINERs.
public final class GuiCopyJavaGenerator {

    private static final MiniMessage MM = MiniMessage.miniMessage();

    private final StringBuilder out = new StringBuilder(2048);

    private GuiCopyJavaGenerator() {
    }

    public static String generate(Inventory inventory) {
        return new GuiCopyJavaGenerator().build(inventory);
    }

    private String build(Inventory inventory) {
        int size = inventory.getSize();
        appendHeader(size);
        for (int i = 0; i < size; i++) {
            ItemStack item = inventory.getItem(i);
            if (item == null || item.getType().isAir()) continue;
            appendSlot(i, item);
        }
        return out.toString();
    }

    private void appendHeader(int size) {
        out.append("// Generated by /guicopy. Paste into a Paper plugin class.\n");
        out.append("//\n");
        out.append("// Required imports:\n");
        out.append("//   import net.kyori.adventure.text.Component;\n");
        out.append("//   import net.kyori.adventure.text.minimessage.MiniMessage;\n");
        out.append("//   import org.bukkit.*;\n");
        out.append("//   import org.bukkit.block.banner.Pattern;\n");
        out.append("//   import org.bukkit.enchantments.Enchantment;\n");
        out.append("//   import org.bukkit.inventory.*;\n");
        out.append("//   import org.bukkit.inventory.meta.*;\n");
        out.append("//   import org.bukkit.persistence.*;\n");
        out.append("//   import org.bukkit.potion.*;\n");
        out.append("//   import io.papermc.paper.registry.RegistryAccess;\n");
        out.append("//   import io.papermc.paper.registry.RegistryKey;\n");
        out.append("//   import java.util.*;\n");
        out.append("//   import java.util.function.Consumer;\n\n");
        out.append("private static final MiniMessage MM = MiniMessage.miniMessage();\n\n");
        out.append("// Place this helper alongside the slot blocks below.\n");
        out.append("private ItemStack buildItem(Material material, int amount, Consumer<ItemMeta> configurer) {\n");
        out.append("    ItemStack item = new ItemStack(material, amount);\n");
        out.append("    item.editMeta(configurer);\n");
        out.append("    return item;\n");
        out.append("}\n\n");
        out.append("// Resolve a registry-keyed object by namespaced key. Used for Enchantments and PotionEffectTypes.\n");
        out.append("private static <T extends Keyed> T registry(RegistryKey<T> registryKey, String key) {\n");
        out.append("    NamespacedKey ns = Objects.requireNonNull(NamespacedKey.fromString(key), \"bad key: \" + key);\n");
        out.append("    return Objects.requireNonNull(RegistryAccess.registryAccess().getRegistry(registryKey).get(ns),\n");
        out.append("            \"missing entry in \" + registryKey + \": \" + key);\n");
        out.append("}\n\n");
        out.append("ItemStack[] contents = new ItemStack[").append(size).append("];\n");
    }

    private void appendSlot(int slot, ItemStack item) {
        out.append('\n');
        out.append("// Slot ").append(slot).append(": ")
                .append(item.getType().getKey().getKey()).append('\n');
        out.append("contents[").append(slot).append("] = buildItem(Material.")
                .append(item.getType().name()).append(", ")
                .append(item.getAmount());

        if (!item.hasItemMeta()) {
            out.append(", meta -> {});\n");
            return;
        }
        out.append(", meta -> {\n");
        ItemMeta meta = item.getItemMeta();
        appendCommonMeta(meta);
        appendSpecializedMeta(meta);
        appendPdc(meta.getPersistentDataContainer());
        out.append("});\n");
    }

    private void appendCommonMeta(ItemMeta meta) {
        if (meta.hasDisplayName()) {
            line(1, "meta.displayName(MM.deserialize(\""
                    + escape(MM.serialize(meta.displayName())) + "\"));");
        }
        if (meta.hasLore()) {
            List<Component> lore = meta.lore();
            line(1, "meta.lore(List.of(");
            for (int i = 0; i < lore.size(); i++) {
                String suffix = i < lore.size() - 1 ? "," : "";
                line(2, "MM.deserialize(\""
                        + escape(MM.serialize(lore.get(i))) + "\")" + suffix);
            }
            line(1, "));");
        }
        if (meta.hasEnchants()) {
            for (Map.Entry<org.bukkit.enchantments.Enchantment, Integer> e
                    : meta.getEnchants().entrySet()) {
                line(1, "meta.addEnchant(registry(RegistryKey.ENCHANTMENT, \""
                        + e.getKey().getKey().asString() + "\"), "
                        + e.getValue() + ", true);");
            }
        }
        Set<ItemFlag> flags = meta.getItemFlags();
        for (ItemFlag flag : flags) {
            line(1, "meta.addItemFlags(ItemFlag." + flag.name() + ");");
        }
        if (meta.hasCustomModelData()) {
            line(1, "meta.setCustomModelData(" + meta.getCustomModelData() + ");");
        }
        if (meta.isUnbreakable()) {
            line(1, "meta.setUnbreakable(true);");
        }
        if (meta instanceof Damageable d && d.hasDamage()) {
            line(1, "((Damageable) meta).setDamage(" + d.getDamage() + ");");
        }
    }

    private void appendSpecializedMeta(ItemMeta meta) {
        if (meta instanceof PotionMeta pm) appendPotion(pm);
        else if (meta instanceof BookMeta bm) appendBook(bm);
        else if (meta instanceof FireworkMeta fm) appendFirework(fm);
        else if (meta instanceof SkullMeta sm) appendSkull(sm);
        else if (meta instanceof LeatherArmorMeta lm) appendLeatherArmor(lm);
        else if (meta instanceof BannerMeta bm) appendBanner(bm);
        else if (meta instanceof EnchantmentStorageMeta esm) appendStoredEnchants(esm);
    }

    private void appendPotion(PotionMeta pm) {
        line(1, "PotionMeta potionMeta = (PotionMeta) meta;");
        if (pm.hasBasePotionType() && pm.getBasePotionType() != null) {
            line(1, "potionMeta.setBasePotionType(registry(RegistryKey.POTION, \""
                    + pm.getBasePotionType().getKey().asString() + "\"));");
        }
        if (pm.hasColor()) {
            Color c = pm.getColor();
            line(1, "potionMeta.setColor(Color.fromRGB("
                    + c.getRed() + ", " + c.getGreen() + ", " + c.getBlue() + "));");
        }
        for (PotionEffect eff : pm.getCustomEffects()) {
            line(1, "potionMeta.addCustomEffect(new PotionEffect("
                    + "registry(RegistryKey.MOB_EFFECT, \""
                    + eff.getType().getKey().asString() + "\"), "
                    + eff.getDuration() + ", " + eff.getAmplifier() + ", "
                    + eff.isAmbient() + ", " + eff.hasParticles() + ", " + eff.hasIcon()
                    + "), true);");
        }
    }

    private void appendBook(BookMeta bm) {
        line(1, "BookMeta bookMeta = (BookMeta) meta;");
        if (bm.hasTitle() && bm.title() != null) {
            line(1, "bookMeta.title(MM.deserialize(\""
                    + escape(MM.serialize(bm.title())) + "\"));");
        }
        if (bm.hasAuthor() && bm.author() != null) {
            line(1, "bookMeta.author(MM.deserialize(\""
                    + escape(MM.serialize(bm.author())) + "\"));");
        }
        for (Component page : bm.pages()) {
            line(1, "bookMeta.addPages(MM.deserialize(\""
                    + escape(MM.serialize(page)) + "\"));");
        }
    }

    private void appendFirework(FireworkMeta fm) {
        line(1, "FireworkMeta fireworkMeta = (FireworkMeta) meta;");
        line(1, "fireworkMeta.setPower(" + fm.getPower() + ");");
        for (FireworkEffect effect : fm.getEffects()) {
            line(1, "fireworkMeta.addEffect(FireworkEffect.builder()");
            line(2, ".with(FireworkEffect.Type." + effect.getType().name() + ")");
            if (effect.hasFlicker()) line(2, ".flicker(true)");
            if (effect.hasTrail()) line(2, ".trail(true)");
            for (Color c : effect.getColors()) {
                line(2, ".withColor(Color.fromRGB("
                        + c.getRed() + ", " + c.getGreen() + ", " + c.getBlue() + "))");
            }
            for (Color c : effect.getFadeColors()) {
                line(2, ".withFade(Color.fromRGB("
                        + c.getRed() + ", " + c.getGreen() + ", " + c.getBlue() + "))");
            }
            line(2, ".build());");
        }
    }

    private void appendSkull(SkullMeta sm) {
        line(1, "SkullMeta skullMeta = (SkullMeta) meta;");
        if (sm.getOwningPlayer() != null && sm.getOwningPlayer().getUniqueId() != null) {
            line(1, "skullMeta.setOwningPlayer(Bukkit.getOfflinePlayer(UUID.fromString(\""
                    + sm.getOwningPlayer().getUniqueId() + "\")));");
        }
    }

    private void appendLeatherArmor(LeatherArmorMeta lm) {
        Color c = lm.getColor();
        line(1, "LeatherArmorMeta leatherMeta = (LeatherArmorMeta) meta;");
        line(1, "leatherMeta.setColor(Color.fromRGB("
                + c.getRed() + ", " + c.getGreen() + ", " + c.getBlue() + "));");
    }

    private void appendBanner(BannerMeta bm) {
        line(1, "BannerMeta bannerMeta = (BannerMeta) meta;");
        for (Pattern p : bm.getPatterns()) {
            NamespacedKey patternKey = RegistryAccess.registryAccess()
                    .getRegistry(RegistryKey.BANNER_PATTERN).getKey(p.getPattern());
            if (patternKey == null) continue;
            line(1, "bannerMeta.addPattern(new Pattern(DyeColor."
                    + p.getColor().name() + ", registry(RegistryKey.BANNER_PATTERN, \""
                    + patternKey.asString() + "\")));");
        }
    }

    private void appendStoredEnchants(EnchantmentStorageMeta esm) {
        line(1, "EnchantmentStorageMeta storageMeta = (EnchantmentStorageMeta) meta;");
        for (Map.Entry<org.bukkit.enchantments.Enchantment, Integer> e
                : esm.getStoredEnchants().entrySet()) {
            line(1, "storageMeta.addStoredEnchant(registry(RegistryKey.ENCHANTMENT, \""
                    + e.getKey().getKey().asString() + "\"), " + e.getValue() + ", true);");
        }
    }

    private void appendPdc(PersistentDataContainer pdc) {
        if (pdc.getKeys().isEmpty()) return;
        line(1, "PersistentDataContainer pdc = meta.getPersistentDataContainer();");
        for (org.bukkit.NamespacedKey key : pdc.getKeys()) {
            String keyExpr = "NamespacedKey.fromString(\"" + key.asString() + "\")";
            appendPdcEntry("pdc", keyExpr, key, pdc);
        }
    }

    // Walks the type table once. Order matters for type-overlap detection — primitives are tried
    // before arrays/containers since the API exposes 'has' per-type independently.
    private void appendPdcEntry(String container, String keyExpr,
                                org.bukkit.NamespacedKey key, PersistentDataContainer pdc) {
        if (pdc.has(key, PersistentDataType.STRING)) {
            line(1, container + ".set(" + keyExpr + ", PersistentDataType.STRING, \""
                    + escape(pdc.get(key, PersistentDataType.STRING)) + "\");");
        } else if (pdc.has(key, PersistentDataType.BOOLEAN)) {
            line(1, container + ".set(" + keyExpr + ", PersistentDataType.BOOLEAN, "
                    + pdc.get(key, PersistentDataType.BOOLEAN) + ");");
        } else if (pdc.has(key, PersistentDataType.LONG)) {
            line(1, container + ".set(" + keyExpr + ", PersistentDataType.LONG, "
                    + pdc.get(key, PersistentDataType.LONG) + "L);");
        } else if (pdc.has(key, PersistentDataType.INTEGER)) {
            line(1, container + ".set(" + keyExpr + ", PersistentDataType.INTEGER, "
                    + pdc.get(key, PersistentDataType.INTEGER) + ");");
        } else if (pdc.has(key, PersistentDataType.SHORT)) {
            line(1, container + ".set(" + keyExpr + ", PersistentDataType.SHORT, (short) "
                    + pdc.get(key, PersistentDataType.SHORT) + ");");
        } else if (pdc.has(key, PersistentDataType.BYTE)) {
            line(1, container + ".set(" + keyExpr + ", PersistentDataType.BYTE, (byte) "
                    + pdc.get(key, PersistentDataType.BYTE) + ");");
        } else if (pdc.has(key, PersistentDataType.DOUBLE)) {
            line(1, container + ".set(" + keyExpr + ", PersistentDataType.DOUBLE, "
                    + pdc.get(key, PersistentDataType.DOUBLE) + ");");
        } else if (pdc.has(key, PersistentDataType.FLOAT)) {
            line(1, container + ".set(" + keyExpr + ", PersistentDataType.FLOAT, "
                    + pdc.get(key, PersistentDataType.FLOAT) + "f);");
        } else if (pdc.has(key, PersistentDataType.BYTE_ARRAY)) {
            line(1, container + ".set(" + keyExpr + ", PersistentDataType.BYTE_ARRAY, new byte[]{"
                    + joinBytes(pdc.get(key, PersistentDataType.BYTE_ARRAY)) + "});");
        } else if (pdc.has(key, PersistentDataType.INTEGER_ARRAY)) {
            line(1, container + ".set(" + keyExpr + ", PersistentDataType.INTEGER_ARRAY, new int[]{"
                    + joinInts(pdc.get(key, PersistentDataType.INTEGER_ARRAY)) + "});");
        } else if (pdc.has(key, PersistentDataType.LONG_ARRAY)) {
            line(1, container + ".set(" + keyExpr + ", PersistentDataType.LONG_ARRAY, new long[]{"
                    + joinLongs(pdc.get(key, PersistentDataType.LONG_ARRAY)) + "});");
        } else if (pdc.has(key, PersistentDataType.TAG_CONTAINER)) {
            PersistentDataContainer nested = pdc.get(key, PersistentDataType.TAG_CONTAINER);
            line(1, "// Nested container at " + key.asString() + ":");
            line(1, "PersistentDataContainer nested_" + safeIdent(key)
                    + " = " + container + ".getAdapterContext().newPersistentDataContainer();");
            for (org.bukkit.NamespacedKey nk : nested.getKeys()) {
                appendPdcEntry("nested_" + safeIdent(key),
                        "NamespacedKey.fromString(\"" + nk.asString() + "\")", nk, nested);
            }
            line(1, container + ".set(" + keyExpr
                    + ", PersistentDataType.TAG_CONTAINER, nested_" + safeIdent(key) + ");");
        } else {
            line(1, "// Unsupported PDC type at " + key.asString());
        }
    }

    private void line(int indent, String text) {
        for (int i = 0; i < indent; i++) out.append("    ");
        out.append(text).append('\n');
    }

    private static String escape(String s) {
        if (s == null) return "";
        StringBuilder b = new StringBuilder(s.length() + 8);
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '\\' -> b.append("\\\\");
                case '"' -> b.append("\\\"");
                case '\n' -> b.append("\\n");
                case '\r' -> b.append("\\r");
                case '\t' -> b.append("\\t");
                default -> {
                    if (c < 0x20) b.append(String.format("\\u%04x", (int) c));
                    else b.append(c);
                }
            }
        }
        return b.toString();
    }

    private static String safeIdent(org.bukkit.NamespacedKey key) {
        return key.asString().replaceAll("[^A-Za-z0-9]", "_");
    }

    private static String joinBytes(byte[] bytes) {
        StringBuilder b = new StringBuilder();
        for (int i = 0; i < bytes.length; i++) {
            if (i > 0) b.append(", ");
            b.append("(byte) ").append(bytes[i]);
        }
        return b.toString();
    }

    private static String joinInts(int[] ints) {
        StringBuilder b = new StringBuilder();
        for (int i = 0; i < ints.length; i++) {
            if (i > 0) b.append(", ");
            b.append(ints[i]);
        }
        return b.toString();
    }

    private static String joinLongs(long[] longs) {
        StringBuilder b = new StringBuilder();
        for (int i = 0; i < longs.length; i++) {
            if (i > 0) b.append(", ");
            b.append(longs[i]).append('L');
        }
        return b.toString();
    }
}