package me.beeliebub.tweaks.tests.commands;

import me.beeliebub.tweaks.commands.GuiCopyJavaGenerator;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.meta.PotionMeta;
import org.bukkit.potion.PotionType;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockbukkit.mockbukkit.MockBukkit;
import org.mockbukkit.mockbukkit.ServerMock;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertTrue;

class GuiCopyJavaGeneratorTest {

    private ServerMock server;

    @BeforeEach
    void setUp() {
        server = MockBukkit.mock();
    }

    @AfterEach
    void tearDown() {
        MockBukkit.unmock();
    }

    @Test
    void generatesHeader() {
        Inventory inv = Bukkit.createInventory(null, 9);
        String output = GuiCopyJavaGenerator.generate(inv);
        assertTrue(output.contains("// Generated by /guicopy"));
        assertTrue(output.contains("private ItemStack buildItem"));
        assertTrue(output.contains("ItemStack[] contents = new ItemStack[9];"));
    }

    @Test
    void generatesSimpleItem() {
        Inventory inv = Bukkit.createInventory(null, 9);
        inv.setItem(0, new ItemStack(Material.DIAMOND, 64));
        String output = GuiCopyJavaGenerator.generate(inv);
        assertTrue(output.contains("contents[0] = buildItem(Material.DIAMOND, 64"));
    }

    @Test
    void generatesItemWithMeta() {
        Inventory inv = Bukkit.createInventory(null, 9);
        ItemStack item = new ItemStack(Material.DIAMOND_SWORD);
        item.editMeta(meta -> {
            meta.displayName(Component.text("Excalibur").color(NamedTextColor.GOLD));
            meta.lore(List.of(Component.text("Legendary Sword")));
            meta.setUnbreakable(true);
        });
        inv.setItem(1, item);

        String output = GuiCopyJavaGenerator.generate(inv);
        assertTrue(output.contains("meta.displayName(MM.deserialize(\"<gold>Excalibur\"));"));
        assertTrue(output.contains("meta.lore(List.of("));
        assertTrue(output.contains("MM.deserialize(\"Legendary Sword\")"));
        assertTrue(output.contains("meta.setUnbreakable(true);"));
    }

    @Test
    void generatesPotionMeta() {
        Inventory inv = Bukkit.createInventory(null, 9);
        ItemStack potion = new ItemStack(Material.POTION);
        potion.editMeta(PotionMeta.class, meta -> {
            meta.setBasePotionType(PotionType.HEALING);
        });
        inv.setItem(2, potion);

        String output = GuiCopyJavaGenerator.generate(inv);
        assertTrue(output.contains("PotionMeta potionMeta = (PotionMeta) meta;"));
        assertTrue(output.contains("potionMeta.setBasePotionType(registry(RegistryKey.POTION, \"minecraft:healing\"));"));
    }
}
